import "./globals.css";
import { Inter, Carattere } from 'next/font/google';
import ClientLayout from "./ClientLayout";

const carattere = Carattere({
  subsets: ["latin"],
  variable: "--font-carattere",
  weight: "400",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${carattere.variable} antialiased`}
      >
       <ClientLayout>
          {children}
        </ClientLayout>
      </body>
    </html>
  );
}
